### ISSUE TITLE
Compare to WorkRave and others

### ISSUE THREAD

**Issue by wolftune** [AllanChain/sane-break#3]
This is superb! The only other I've seen that prompts the break without forcing it, allowing natural transition…

Which is what WorkRave does https://workrave.org/

I would love to see a comparison or to see sane-break incorporate any missing features that WorkRave has and which would be appropriate.

Personally, I always go back to WorkRave after trying SafeEyes or Stretchly or others because exactly this style of prompt and transition is key.

WorkRave has supporting widgets such as https://github.com/wojnilowicz/workrave-applet for KDE and others, this shows a visual timer, and all in all WorkRave is just superb but it does have an old-time UI and does not have customizable notes to display during breaks the way SafeEyes and Stretchly do…

**Comment by AllanChain** [comment]
Thanks for mentioning WorkRave. I have tried it long time ago and gave up shortly afterwards. I can remember the exact reason now, probably because of the old UI. And I will check it and add the comparison.

**Comment by AllanChain** [comment]
The stable release of Workrave does not support Wayland, and that's why I gave it up. After trying out latest Workrave (1.11.0-beta.15), I still find it very buggy on Wayland:
1. It always thinks me ignoring the break.
2. After breaks, the tray menus are gone.
3. Rest break exits after a while with no reason.

Since my main working environment is KDE Wayland, (and occasionally macOS and rarely Windows), Workrave is simply not working for me.

Based on my observations, I think Sane Break are pretty similar to Workrave, except for the following difference: Sane Break waits until you finished working and starts break right after you are finished, while with Workrave, if you missed once, will try again later or force you break. I have no way to start micro breaking if Workrave is not asking, and have to wait until it shows up, which might be a frustrating force break.

As for the applet, Sane Break is designed to deliver rich information from just the tray icon. The circle around the tray icon indicates the remaining time for the next break. Therefore, I don't think there is a need to include an applet.

But again, I haven’t tried Workrave, so my opinion might not be accurate. I would be glad to hear from Workrave users and learn about their thoughts on what makes for a good break reminder.

**Comment by wolftune** [comment]
Yeah, I couldn't work well with any of the others besides WorkRave until I learned about sane-break ­— and I went back to x from Wayland on KDE just for WorkRave!

I will test Sane-break and see what I most miss from WorkRave. For me, a KDE-6-Wayland WorkRave-style thing sounds superb, and newer UI is very nice too. Thank you so much. I'll say more soon after testing

**Comment by wolftune** [comment]
To respond to your review above:

First, yes WorkRave is not fully there for Wayland yet.

>  I have no way to start micro breaking if Workrave is not asking, and have to wait until it shows up, which might be a frustrating force break.

WorkRave just treats it as a break when you are idle, and the mini-view and applet show the break adding up until it gets full (which counts as a successful break), it just doesn't do the full-screen break view. You can also use the contextual menu to start breaks.

I like sane-break better — it's nicer for the nag-warning to just stick around until I'm ready to break (and to force it after some settable amount of time).

On the applet, sane-break is adequate as is. The reason I emphasized WorkRave applet is that the extra applet *is* needed for a better WorkRave experience if one were to compare fairly.

If you'd like me to open separate issues for items in my comparison above to consider adding to sane-break, let me know. Some of the items would really be worthwhile.

I also could imagine some summary comparison put in the README or similar, but that can be annoying to maintain as programs change over time.

**Comment by AllanChain** [comment]
Thank you so much for the super detailed review! Your advice is really helpful, and I appreciate it so much. Personally, I would rank the priority of the features roughly as:

1. 🚧 media controls
2. 🚧 pause for specific window settings (particular programs or full-screen windows)
3. 🚧 nag box moves
4. 😄 reading-mode (breaks even if idle detected)
5. 😄 audible bells
6. 🚧 controls during break for lock/suspend/shutdown
7. 😄 customizable break messages
8. 😖 daily limit
9. 😖 stats

(🚧: need to do it for all platforms, may be hard; 😄 relatively easy task; 😖 complex)

I put feature 5-9 to lower priority because I personally will never use them:

5. audible bells: I'm working in an office shared with other people, and I'm not always wearing a headphone.
6. lock control: I can always lock using keyboard shortcuts.
7. customizable break messages: I know what to do for a break.
8. daily limit: I don't see this will help me. This can only interrupt me in the evening and I will turn to use smartphones, which is no better.
9. stats: I never read the stats when I was using RSIBreak.

---

> If you'd like me to open separate issues for items in my comparison above to consider adding to sane-break, let me know. Some of the items would really be worthwhile.

I will open the issues.

> I also could imagine some summary comparison put in the README or similar, but that can be annoying to maintain as programs change over time.

This is indeed annoying and can sometimes offend developers for other alternatives. My current strategy is to only highlight our features in README.

**Comment by wolftune** [comment]
Nicely put! For perspective my personal take:



> * 🚧 media controls

I've never used media controls, I can pause something before the break or allow something to play during it, I don't really care about it myself.

> * 🚧 pause for specific window settings (particular programs or full-screen windows)

I might really use this. It's much cleaner than postponing or quitting during some focused thing

> * 🚧 nag box moves

Nag box hasn't really gotten in my way yet, but it might, this would be great to have

> * 😄 reading-mode (breaks even if idle detected)

Not sure, I can do some random activity, like scrolling and whatever while reading, and that will probably keep the breaks coming…

> * 😄 audible bells

I would appreciate this, but also my young son on his computer, it would keep him more accountable. And it helps avoid the temptation to check if the break is over yet.

> * 🚧 controls during break for lock/suspend/shutdown

Mostly during long-breaks, there's even a security risk if leaving the computer but not having it locked. And sometimes a long break is the right time to take an extended break for a totally different activity or errands or something. And to save power. This would be one I'd consider higher priority.

> * 😄 customizable break messages

Some people like these. I'm getting more like you, I want to look away from screen, not look at it for what to do. But customizable messages can be set to remind us of exactly things we personally need reminders of… I would like to see this feature.

> * 😖 daily limit

Daily limit is actually quite important for younger kids, like my son. He has no cell phone. Keeping a daily limit is really nice and something we use WorkRave for. And I'd like it for other families to recommend for their kids. Kids can bypass it too, there's still trust involved, but that's part of the whole picture.

> * 😖 stats

If there's a daily-limit, it needs to keep some stats anyway, but I've never really cared about stats myself

**Comment by AllanChain** [comment]
I have created relevant issues with priorities assigned:

- High #9
- Medium #10
- Medium #11
- Medium #12
- Medium #13
- Low #14 
- Low #15

A question regarding auto lock/suspend/shutdown: Do you mean adding buttons for lock/suspend/shutdown when the break is forced? When the break is not forced, I can always use system menus to do the job. Even when the break is forced, I can use <kbd>Win</kbd>+<kbd>L</kbd> to lock screen and there is no security issue.

**Comment by wolftune** [comment]
I'm guessing Win+L is a system thing? Or is that a sane-break function? I've never used that and it doesn't work for me in testing outside of sane-break on my system.

I can suspend my system with physical power button, but that might not work for some setups.

FWIW, WorkRave has on-screen button (with a drop-down menu) for lock/suspend/shutdown as part of the break screen. I'm not insisting that it is needed, but it is part of the comparison. I agree that pre-force anything is trivial so it seems okay to not have this.

**Comment by AllanChain** [comment]
Yes, Win+L is a system thing. I thought it is the default key binding for KDE.

**Comment by wolftune** [comment]
Win+L (or rather "Meta+L") is indeed listed as a default, but it wasn't *checked* for some reason in my settings. It does indeed lock. And I can set a shortcut for suspend too. I think that resolves the issue enough.

**Comment by wolftune** [comment]
Closing this as complete enough, other issues opened and all
